### PR TITLE
Improve testing against multiple backends

### PR DESCRIPTION
**Pull request by nicholalexander**
This is only a change for `queue_collection_spec.rb`
- based on some of the thoughts from steve's blog post and HWIA thread, use strings instead of symbols in tests.  
- loop through backends and run each test against each backend.

Is this better than shared examples?

### CODE REVIEW

**Comment by alecclarke** [comment]
> Is this better than shared examples?

I like this a lot! What does it look like when one adapter fails a test? Is it easy to debug?

**Comment by nicholalexander** [comment]
ugh - it's horrible - you have no idea where it fails!  i played with trying to add in some notifications but it's very hacky and still not very nice.

**Comment by nicholalexander** [comment]
ok, here's what i got with shared examples.  its verbose so that should help, and it fails nicely.  what do ya think?

**Comment by alecclarke** [comment]
Looks great! A good use of shared examples!

**Review by alecclarke — APPROVED** [review]

**Pull request merged**
